name: bento_build
on:
  # push:
  #   branches:
  #     - 'main'
  workflow_dispatch:      

jobs:
  build_bento:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: installing packages
        run: pip install -r requirements.txt
      - name: train bentomodel
        run: python train.py
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: bentoml/build-bento-action@v1
        id: bento
      - name: Build and push BentoContainer
        uses: bentoml/containerize-push-action@v1
        with:
          bento-tag: ${{ steps.bento.outputs.bento-tag }}
          push: true
          tags: mj703/iris_classifier:v1.0.1